services:
  # 1. API OpenDSS
  opendss:
    build: .
    command: python -m simulators.opendss.api_opendss --remote 0.0.0.0:5671
    ports:
      - "5671:5671"
    volumes:
      - ./src:/app/src
      - ./data:/app/data

  # 2. Simulador de Bateria
  battery:
    build: .
    command: python -m simulators.battery.battery_sim --remote 0.0.0.0:5672
    ports:
      - "5672:5672"
    volumes:
      - ./src:/app/src
      - ./data:/app/data

  # 3. Coletor de Dados
  collector:
    build: .
    command: python -m simulators.collector.collector --remote 0.0.0.0:5673
    ports:
      - "5673:5673"
    volumes:
      - ./src:/app/src
      - ./output:/app/output

  # 4. Simulador do Controlador da Bateria
  controller:
    build: .
    command: python -m simulators.controller.controller_sim --remote 0.0.0.0:5674
    ports:
      - "5674:5674"
    volumes:
      - ./src:/app/src

  # 5. Simuladores CSV
  csv-data-1:
    build: .
    command: python -m simulators.collector.csv_sim_pandas --remote 0.0.0.0:5675
    ports:
      - "5675:5675"
    volumes:
      - ./src:/app/src
      - ./data:/app/data

  csv-data-2:
    build: .
    command: python -m simulators.collector.csv_sim_pandas --remote 0.0.0.0:5676
    ports:
      - "5676:5676"
    volumes:
      - ./src:/app/src
      - ./data:/app/data

  # 6. Simulador de Inversor Padrão
  inverter-std:
    build: .
    command: python -m simulators.inverter.inverter_simulator --remote 0.0.0.0:5677
    ports:
      - "5677:5677"
    volumes:
      - ./src:/app/src

  # 7. Simulador de Painéis PV
  pv-panel:
    build: .
    command: python -m simulators.pv.pv_panel_simulator --remote 0.0.0.0:5678
    ports:
      - "5678:5678"
    volumes:
      - ./src:/app/src

  # 8. Controle de Regulador de Tensão
  regulator:
    build: .
    command: python -m simulators.controller.regulator_control --remote 0.0.0.0:5679
    ports:
      - "5679:5679"
    volumes:
      - ./src:/app/src

  # 9. Smart Inverter (OpenDER)
  smart-inverter:
    build: .
    command: python -m simulators.inverter.smart_inverter_simulator --remote 0.0.0.0:5680
    ports:
      - "5680:5680"
    volumes:
      - ./src:/app/src
